# Generated by Django 4.2.4 on 2023-09-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile',
            field=models.ImageField(upload_to='manager_pic'),
        ),
    ]
